name: Deploy-Blog

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: deploy blog
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true # Checkout private submodules(themes or something else).

    - name: Set timezone
      uses: szenius/set-timezone@v1.2
      with:
        timezoneLinux: "Asia/Taipei"

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Cache NPM dependencies
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.OS }}-npm-cache
        restore-keys: |
          ${{ runner.OS }}-npm-cache

    - name: Install Dependencies
      run: |
        npm install

    - name: Update _config.yml with secrets
      run: |
        # Update root config
        sed -i "s/FIRESTORE_API_KEY/${{ secrets.FIRESTORE_API_KEY }}/g" _config.yml
        sed -i "s/FIRESTORE_PROJECT_ID/${{ secrets.FIRESTORE_PROJECT_ID }}/g" _config.yml

    - name: Build
      run: npm run build

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./public

  deploy:
      needs: build
      permissions:
        pages: write
        id-token: write
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4